apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-01-25T22:57:48Z"
  generation: 1
  labels:
    app: api
  name: api
  namespace: default
  resourceVersion: "82340"
  selfLink: /apis/apps/v1/namespaces/default/deployments/api
  uid: 66009988-8a6d-4e61-a790-7123a7b3c0ca
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
        name: api
    spec:
      containers:
      - image: acr527117.azurecr.io/content-api
        env:
        - name: MONGODB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: cosmosdb
              key: db        
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: api
        ports:
        - containerPort: 3001
          hostPort: 3001
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 128Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-01-25T22:57:48Z"
    lastUpdateTime: "2022-01-25T22:58:03Z"
    message: ReplicaSet "api-79c5d8dfb9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-25T23:04:08Z"
    lastUpdateTime: "2022-01-25T23:04:08Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
